### ISSUE TITLE
Permissions based crash on OS X 10.14+

### ISSUE THREAD

**Issue by vonnieda** [openpnp/openpnp-capture#31]
Noticed last night that openpnp-capture was crashing when trying to open a camera on OS X. Seems to be related to the required permissions to use the camera on OS X 10.14+.

```
==============================
 OpenPNP Capture Test Program
 OSX 64 bit debug v0.0.17 Jan 22 2020 
==============================
Usage: openpnp-capture-test <camera ID> <frame format ID>

..continuing with default camera parameters.

[INFO] Platform context created
2020-01-22 23:38:36.655841-0600 openpnp-capture-test[28601:4534687] authorizationStatusForMediaType 0
2020-01-22 23:38:36.656261-0600 openpnp-capture-test[28601:4534687] authorizationStatusForMediaType 0
[DBG ] enumerateDevices called
2020-01-22 23:38:36.658600-0600 openpnp-capture-test[28601:4535236] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.
```

As far as I can tell we need to call:

```
    [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted) {
    } ];
```

But this requires that the app has an Info.plist, and I think that has to be part of the package that library is used in, rather than the library itself. Continuing to investigate this.

**Comment by vonnieda** [comment]
Confirmed that adding the above code and an Info.plist in the binary directory works.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>I need it.</string>
</dict>
</plist>
```

**Comment by trcwm** [comment]
Does this require a code change for OSX? Maybe something to gracefully abort rather than crashing?

**Comment by vonnieda** [comment]
@trcwm Yep, it requires a code change. I fixed this recently and released a new version that handles it but forgot to close this issue. See https://github.com/openpnp/openpnp-capture/commit/082959e1a281c45c7acf638eb3e3b90127b12051

**Comment by trailhead** [comment]
I'm still seeing a crash when adding cameras in the June 28 build on OSX 10.11.6.  I think that's the most recent OSX I can run on that machine.  Looking at the error report I see:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AVCaptureDevice authorizationStatusForMediaType:]: unrecognized selector sent to class 0x7fff790ca768'
terminating with uncaught exception of type NSException

**Comment by vonnieda** [comment]
Looks like that version of OSX didn't have the permission check API, so we
need to add a check if the API is available before calling it.

**Comment by trailhead** [comment]
For anyone else having this issue, I upgraded to Mojave and that solved it.
